# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'aries' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for aries
  pod "youtube-ios-player-helper", "~> 1.0.4"

  target 'ariesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ariesUITests' do
    # Pods for testing
  end

end
